### ISSUE TITLE
Gnome session dies on pandas_profiling.ProfileReport(df)

### ISSUE THREAD

**Issue by kuratsak** [pandas-profiling/pandas-profiling#34] opened 2017-01-02 12:29 UTC
Just ran in ipython locally on my machine and the whole gnome session died - couldnt bring it back until full machine restart.
does that make any sense?

**Comment by JosPolfliet** [comment] 2017-01-02 13:18
Which gnome version and browser are you using? Did your dataset have a lot of variables in it? That could cause rendering issues. That would more be a bug in your browser. Can you please save your work and try to recreate it? Preferably use a small file.

**Comment by kuratsak** [comment] 2017-01-02 13:41
I had about 6k rows, a dozen or so variables.
My chrome did get seriously broken (newest chrome). Gnome is the default
one which comes with trusty 14.04 Ubuntu.

**Comment by conradoqg** [comment] 2018-01-05 02:26
Hey,

With the above PR #82 merged, you can:

- Use the parameter pandas_profiling.ProfileReport(df, check_recoded = False) to alleviate memory pressure and at the same time get the correlation report. The recoded checking is indeed memory heavy.
I think we can close this issue after those changes. Since the post author hasn't given a reproducible way to check this.

Best

**Comment by romainx** [comment] 2018-01-06 15:38
OK, I close it.
Thanks

**Closed by romainx** 2018-01-06 15:38 UTC
