### ISSUE TITLE
pandas profilling too dlow: make multi processing

### ISSUE THREAD

**Issue by arita37** [pandas-profiling/pandas-profiling#741] opened 2021-03-30 06:11 UTC
Have a stable of 10000 rows, 4000 columns,
panda profile is too slow...

Can you make it in multi-processing ?
(ie column stats can be done in multi-processing easily).

thanks

**Comment by sbrugman** [comment] 2021-04-02 09:43
The `pool_size` parameter can currently be used ([relevant code](https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/summary.py#L83)). Possible duplicate of #743.

**Closed** 2021-09-27 22:45 UTC
Labels: performance 🚀
