### ISSUE TITLE
Number of specified cores not being utilised

### ISSUE THREAD

**Issue by Peji-moghimi** [pandas-profiling/pandas-profiling#474] opened 2020-05-14 21:21 UTC
Hi, 

This could point to a potential bug/improvement, though currently is more of a question.
I have specified 38 cores in my config.yaml file, however, over the past 24 hours that I have been running pandas_profiling only 4 cores have been used, whilst being stuck at variable 13/17, which is the first column with loads of NaN values.
Is this normal behaviour? And what is the reason for using a small subset of the available cores when multiprocessing is possible?

Thank you!

**Comment by sbrugman** [comment] 2020-05-14 21:35
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by loopyme** [comment] 2020-05-15 02:51
I believe this behavior is normal at this stage, which is due to the large granularity of the tasks.

Currently, PP is building report in pipeline-like pattern, and the following calculation (plotting, rendering) shall be carried out after the variable description is completed. That is, all variable descriptions need to be completed first, and each variable description job takes up one kernel, however describe some variable may take more time (in your case, there are four variables take up a lot of time, so only four kernels is working).

I guess there is no quick fix for now, but you can always adjust config to reduce computation. This problem may be addressed in the future by introducing the task graph pattern

**Comment by Peji-moghimi** [comment] 2020-05-15 08:14
Thank you @loopyme! That was helpful. 

I would need to familiarise myself with the source code before I can be sure, but, I think these variables take so long because, as oppose to the other columns with no NaN values, they are filled with NaN values. 
The task graph pattern sounds like a great solution, though, perhaps it would also be very helpful in the mean time, if possible, to modify the tqdm progress bar to be updated by every task completion (as in the tasks in the pipeline that you mentioned), as well as by variable. This would give an idea of per variable time-complexity, and in the case of big datasets like mine the progress bar getting stuck at a single variable for days would not appear as some sort of uncaught error/infinite loop, if it is visible that the tasks are being completed. This could also help a lot in making decisions about adjusting the config file, in my case for instance, to set all missing values calculations to False.

**Comment by loopyme** [comment] 2020-05-15 09:04
Hi @Peji-moghimi , glad that the information is helpful!

As for the unacceptable slowness problem, could you provide the minimal information to reproduce it like @sbrugman mention before?

About the process bar, the more detailed precision bar for quick diagnosis you mentioned  sounds great. However, as far as I know, the 'variable' progress bar actually display the summary stage of the pipeline (`summary`->`build report`->`render`) and ‘Summary about one variable’ is by far the atomic task. We may need more fine-grained task partitioning to support this feature.

**Comment by sbrugman** [comment] 2020-05-15 11:42
To contribute to this topic: optimizing the scheduling of tasks as @loopyme proposes is one of the ways forward. Moreover, choosing for finer-grained task partitioning will provide the user with better diagnositics (such as the progress bar you're mentioning).

However, this doesn't solve the problem at all if the complexity of a specific comutation is disproportionate. In that scenario, for a large dataset, you still will wait for few workers to finish. That's why it's important to provide the minimal information as I mentioned before.

**Comment by Peji-moghimi** [comment] 2020-05-15 20:43
**Data and code:**

```
profiling_df = pd.read_csv(os.path.join(root_dir, dataset_dir, "profiling_report_df.csv"))
profiling_df 
```

col_1 | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | col_9 | col_10 | col_11 | col_12 | col_13 | col_14 | col_15 | col_16
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
IGHV3-30*18 | IGHV3-30 | IGHJ5*02 | IGHJ5 | 11 | 40 | 98.795181 | 1 | IgM | 104 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV4-59*01 | IGHV4-59 | IGHJ6*02 | IGHJ6 | 20 | 38 | 98.809524 | 1 | IgM | 112 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV3-23*01 | IGHV3-23 | IGHJ4*02 | IGHJ4 | 18 | 36 | 98.837209 | 1 | IgM | 113 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV3-30*18 | IGHV3-30 | IGHJ5*02 | IGHJ5 | 11 | 40 | 100.000000 | 0 | IgM | 104 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV3-23*01 | IGHV3-23 | IGHJ5*02 | IGHJ5 | 11 | 40 | 97.590361 | 2 | IgM | 104 | 1 | 1 | NaN | NaN | NaN | NaN
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
IGHV1-69*13 | IGHV1-69 | IGHJ4*02 | IGHJ4 | 14 | 43 | 98.795181 | 1 | IgM | 106 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV4-59*02 | IGHV4-59 | IGHJ5*02 | IGHJ5 | 18 | 38 | 95.238095 | 4 | IgM | 111 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV3-21*02 | IGHV3-21 | IGHJ4*02 | IGHJ4 | 8 | 41 | 90.476190 | 8 | IgM | 101 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV4-59*10 | IGHV4-59 | IGHJ5*02 | IGHJ5 | 14 | 42 | 97.590361 | 2 | IgM | 106 | 1 | 1 | NaN | NaN | NaN | NaN
IGHV3-30*02 | IGHV3-30 | IGHJ4*02 | IGHJ4 | 17 | 38 | 97.647059 | 2 | IgM | 111 | 1 | 1 | NaN | NaN | NaN | NaN

49000967 rows × 16 columns

```
grouped_subsett = unified_merged_copy.groupby('col_11')
test_profile_subset = grouped_test_profile_subset.progress_apply(lambda x: x.sample(frac=0.001))
test_profile_subset.info()
```

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49001 entries, (1, 21498621) to (8, 2180161)
Data columns (total 16 columns):

 index | Column | Non-Null | Count | Dtype  
---  ------  --------------  -----  
 0   col_1   49001 non-null  object 
 1   col_2   49001 non-null  object 
 2   col_3   49001 non-null  object 
 3   col_4   49001 non-null  object 
 4   col_5   49001 non-null  int64  
 5   col_6   49001 non-null  int64  
 6   col_7   49001 non-null  float64
 7   col_8   49001 non-null  int64  
 8   col_9   49001 non-null  object 
 9   col_10  49001 non-null  int64  
 10  col_11  49001 non-null  int64  
 11  col_12  49001 non-null  int64  
 12  col_13  773 non-null    float64
 13  col_14  920 non-null    float64
 14  col_15  668 non-null    float64
 15  col_16  815 non-null    float64
dtypes: float64(5), int64(6), object(5)
memory usage: 6.6+ MB

```
test_profile_subset_2 = grouped_test_profile_subset.progress_apply(lambda x: x.sample(frac=0.01))
test_profile_subset = test_profile_subset.reset_index(drop=True)
test_profile_subset_2 = test_profile_subset_2.reset_index(drop=True)
test_profile_subset_3 = test_profile_subset.fillna(value=0)
test_profile_subset_4 = test_profile_subset_2.fillna(value=0)
```
```
%time test_profile_report = ProfileReport(test_profile_subset, config_file='test_profiling_config_1.yaml')
```
takes 2 mins to run
```
%time test_profile_report_2 = ProfileReport(test_profile_subset_2, config_file='test_profiling_config_1.yaml')
```
Takes 87 minutes to run

```
%time test_profile_report_5 = ProfileReport(test_profile_subset_3, config_file='test_profiling_config_1.yaml')
```
Takes 46 seconds to run
```
%time test_profile_report_6 = ProfileReport(test_profile_subset_4, config_file='test_profiling_config_1.yaml')
```
<strong><em>***Takes 139 seconds to run, which, makes it fairly conclusive that something in the description pipeline is causing issues when there are disproportionately large number of NaN values in variable.***</em></strong>

* _Python version_: 3.8.2.
* _Environment_: Jupyter lab

<details><summary>
pip freeze:
<strong><em>packages</em></strong></summary>
<p>
aiohttp==3.6.2
altair==4.1.0
appdirs==1.4.3
astropy==4.0.1.post1
async-timeout==3.0.1
attrs==19.3.0
autopep8==1.5.2
backcall==0.1.0
biopython==1.76
black==19.10b0
bleach==3.1.4
bokeh==2.0.2
CacheControl==0.12.6
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.1
colorama==0.4.3
confuse==1.1.0
cryptography==2.8
cycler==0.10.0
Cython==0.29.17
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
entrypoints==0.3
fastprogress==0.2.3
gitdb==4.0.4
GitPython==3.1.1
hdmedians==0.13
htmlmin==0.1.12
idna==2.9
ImageHash==4.1.0
importlib-metadata==1.6.0
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.11.2
joblib==0.14.1
json5==0.9.0
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-conda==3.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server-proxy==1.3.2
jupyterlab==2.1.0
jupyterlab-code-formatter==1.2.3
jupyterlab-git==0.10.0
jupyterlab-nvdashboard==0.2.1
jupyterlab-server==1.1.1
kiwisolver==1.2.0
llvmlite==0.32.0
lockfile==0.12.2
lxml==4.5.0
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.2.1
missingno==0.4.2
mistune==0.8.4
more-itertools==8.2.0
msgpack==1.0.0
multidict==4.7.5
natsort==7.0.1
nb-conda-kernels==2.2.3
nbconvert==5.6.1
nbdime==1.1.0
nbformat==5.0.4
networkx==2.4
notebook==6.0.3
numba==0.49.0
numpy==1.18.2
packaging==20.3
pandarallel==1.4.8
pandas==1.0.3
pandas-profiling==2.6.0
pandocfilters==1.4.2
panel==0.9.5
param==1.9.3
parso==0.7.0
pathspec==0.8.0
patsy==0.5.1
pexpect==4.8.0
phik==0.9.11
pickleshare==0.7.5
Pillow==7.1.1
plotly==4.7.0
pluggy==0.13.1
prometheus-client==0.7.1
prompt-toolkit==3.0.5
psutil==5.7.0
ptvsd==4.3.2
ptyprocess==0.6.0
py==1.8.1
pycodestyle==2.5.0
pycparser==2.20
pyct==0.4.6
Pygments==2.6.1
pynvml==8.0.4
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.16.0
PyScaffold==3.2.3
PySocks==1.7.1
pytest==5.4.1
python-dateutil==2.8.1
pytz==2020.1
pyviz-comms==0.7.4
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
regex==2020.4.4
requests==2.23.0
retrying==1.3.3
rpy2==3.3.2
scikit-bio==0.5.6
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.1
Send2Trash==1.5.0
simpervisor==0.3
six==1.14.0
smmap==3.0.2
statsmodels==0.11.1
tangled-up-in-unicode==0.0.4
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
tzlocal==2.0.0
urllib3==1.25.8
vega-datasets==0.8.0
visions==0.4.1
wcwidth==0.1.9
webencodings==0.5.1
widgetsnbextension==3.5.1
yarl==1.4.2
zipp==3.1.0 
```

</p>
</details>

<details><summary>
config.yaml:
<strong><em>content</em></strong></summary>
<p>
config.yaml file
title: Pandas Profiling Report
pool_size: 35
progress_bar: yes
vars:
    num:
        quantiles:
        - 0.05
        - 0.25
        - 0.5
        - 0.75
        - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 5
        chi_squared_threshold: 0.999
    cat:
        check_composition: yes
        cardinality_threshold: 50
        n_obs: 5
        chi_squared_threshold: 0.999
    bool:
        n_obs: 3
sort: ascending
missing_diagrams:
    bar: no
    matrix: no
    heatmap: no
    dendrogram: no
correlations:
    pearson:
        calculate: yes
        warn_high_correlations: yes
        threshold: 0.9
    spearman:
        calculate: yes
        warn_high_correlations: no
    kendall:
        calculate: yes
        warn_high_correlations: no
    phi_k:
        calculate: yes
        warn_high_correlations: no
    cramers:
        calculate: yes
        warn_high_correlations: yes
        threshold: 0.9
    recoded:
        calculate: no
        warn_high_correlations: no
        threshold: 0.0
interactions:
    continuous: yes
categorical_maximum_correlation_distinct: 100
plot:
    image_format: svg
    dpi: 800
    correlation:
        cmap: RdBu
        bad: '#000'
    missing:
        cmap: RdBu
        force_labels: yes
    histogram:
        bayesian_blocks_bins: yes
        bins: 50
n_obs_unique: 5
n_extreme_obs: 5
n_freq_table_max: 10
samples:
    head: 10
    tail: 10
reject_variables: yes
notebook:
    iframe:
        height: 800px
        width: 100%
        attribute: srcdoc
html:
    style:
        full_width: yes
        theme: flatly
        logo: ''
        primary_color: '#337ab7'
    minify_html: yes
    use_local_assets: yes
    navbar_show: yes
</p>
</details>

**Comment by Peji-moghimi** [comment] 2020-05-15 20:47
@sbrugman @loopyme, sorry about the late upload. I intended this just to be a question, but since I would really like this to work and you asked, I though I dosome shallow testing and from the results it's conclusive that once the NaN values are replaced by zeros, the time-complexity is 1/47 to a comparable dataset with all NaN values intact.

**Comment by sbrugman** [comment] 2020-05-15 21:17
Will look into it, thanks @Peji-moghimi.

**Comment by sbrugman** [comment] 2020-05-16 00:19
@Peji-moghimi The config file is very inclusive, but you have also tried `minimal=True` mode, which restricts the search space for the root cause to the variables (since you've also reported that the parallism is suboptimal at the end of analysing the variables).

I've worked through that part of the code and could not find large differences between series with a high number of NaNs or fully filled NaNs.

One of the reasons might be that you're running v2.6.0. The last releases have included significant performance improvements. Please let me know if updating resolves the problem. If not, then it would be helpful to share the CSV file you've used.

**Comment by Peji-moghimi** [comment] 2020-05-18 18:55
@sbrugman To my pleasant surprise not only the update did it, the whole thing was done in just over an hour. Great job on the new version!
Thank you for the help, and soon I'll create a separate post about contributing to the package by bringing in some genomics sequence analysis. Would you be interested?

**Comment by sbrugman** [comment] 2020-05-18 18:58
> @sbrugman To my pleasant surprise not only the update did it, the whole thing was done in just over an hour. Great job on the new version!
> Thank you for the help, and soon I'll create a separate post about contributing to the package by bringing in some genomics sequence analysis. Would you be interested?

Thanks for the feedback. New types of analyses are very welcome, feel free to open an issue or PR in case of questions during development.

**Closed by sbrugman** 2020-05-18 18:58 UTC
