### ISSUE TITLE
ZeroDivisionError when using version 1.4.1

### ISSUE THREAD

**Issue by ojarjur** [pandas-profiling/pandas-profiling#94] opened 2018-01-10 23:56 UTC
There was a change in behavior between versions 1.4.0 and 1.4.1 where some calls to `ProfileReport` that previously succeeded will now raise a ZeroDivisionError.

An example reproduction is to take the following code and run it in a Jupyter notebook cell:

```py
import pandas
import pandas_profiling

import IPython

df = pandas.DataFrame({'c': 'v'}, index=['c'])
report = pandas_profiling.ProfileReport(df)
IPython.core.display.HTML(report.html)
```

With version 1.4.0 this produced an HTML report, but with version 1.4.1 it produces the following stack trace:

```
ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-2-ffb5392b4284> in <module>()
      5 
      6 df = pandas.DataFrame({'c': 'v'}, index=['c'])
----> 7 report = pandas_profiling.ProfileReport(df)
      8 IPython.core.display.HTML(report.html)

/usr/local/lib/python2.7/dist-packages/pandas_profiling/__init__.pyc in __init__(self, df, **kwargs)
     67 
     68         self.html = to_html(sample,
---> 69                             description_set)
     70 
     71         self.description_set = description_set

/usr/local/lib/python2.7/dist-packages/pandas_profiling/report.pyc in to_html(sample, stats_object)
    192 
    193     # Add plot of matrix correlation
--> 194     pearson_matrix = plot.correlation_matrix(stats_object['correlations']['pearson'], 'Pearson')
    195     spearman_matrix = plot.correlation_matrix(stats_object['correlations']['spearman'], 'Spearman')
    196     correlations_html = templates.template('correlations').render(

/usr/local/lib/python2.7/dist-packages/pandas_profiling/plot.pyc in correlation_matrix(corrdf, title, **kwargs)
    134     plt.title(title, size=18)
    135     plt.colorbar(matrix_image)
--> 136     axes_cor.set_xticks(np.arange(0, corrdf.shape[0], corrdf.shape[0] * 1.0 / len(labels)))
    137     axes_cor.set_yticks(np.arange(0, corrdf.shape[1], corrdf.shape[1] * 1.0 / len(labels)))
    138     axes_cor.set_xticklabels(labels, rotation=90)

ZeroDivisionError: float division by zero
```

**Comment by znwang25** [comment] 2018-01-18 19:45
I have the same error. Is there any updates on this issue?

**Comment by AFTRTCH** [comment] 2018-01-31 01:03
Same issue.

**Comment by Aylr** [comment] 2018-02-06 05:03
There is a PR in to fix this. In the interim downgrade to 1.4.0:

```
pip uninstall pandas_profiling
pip install 'pandas_profiling==1.4.0'
```

**Comment by exetera** [comment] 2018-02-06 16:50
Hi,
I got the same error also with the 1.4.0 version...

How can I fix it?

**Comment by shashankumar2812** [comment] 2018-03-20 19:23
I am facing the same issue. Has the issue been resolved?

**Comment by wdescamps** [comment] 2018-07-10 12:10
In my case, it appeared as i had values with a comma instead of a decimal point ("0,1" vs "0.1"). Changing those values to decimal points solved it for me. :)

**Comment by RAFFSIMOMS** [comment] 2018-07-24 07:53
anyone got a fix?

**Comment by courtneypk-work** [comment] 2018-08-06 19:16
In my case, it was because I was looking at a dataframe which I had imported from a csv as all strings using `pandas.read_csv(file, dtype='str')`. The dataset was read in like this because pandas does a lousy job of inferring data types. I realized this was a problem since the error was ultimately here

>   File "/usr/lib/python3.4/site-packages/pandas_profiling/plot.py", line 136, in correlation_matrix
    axes_cor.set_xticks(np.arange(0, corrdf.shape[0], corrdf.shape[0] * 1.0 / len(labels)))

and of course there is no correlation between strings. Taking the argument out of `read_csv` eliminated the error.

**Comment by SundaresanGanapathy** [comment] 2018-10-22 16:28
I am getting ZeroDivisionError for a valid simple data set, tried by downgrading to 1.4.0 but program runs infinitely   without any success/failure message, any idea which version is stable enough for production usage ?

**Comment by rubenflamshepherd** [comment] 2018-11-27 17:08
So I ran into this issue and in my case the cause was because all the columns in my dataframe were 'object' datatype. I ran `df.infer_objects()` which managed to type one of the columns and from there ProfileReport worked. Hope this helps!

**Comment by stevenrouk** [comment] 2019-02-05 21:56
I solved this for my data by adding in a non-object dtype column—something simple like `df["ignore"] = 0`.

All of my columns in my original data were of type `object`, and it was throwing the `ZeroDivisionError` when it got to the part of the script that calculations correlation, so I think what was happening was that it didn't have any fields to use in the correlation plot and thus had 0 length sides or something like that.

**Comment by JosPolfliet** [comment] 2019-04-27 08:40
should be fixed

**Closed by JosPolfliet** 2019-04-27 08:40 UTC

**Comment by galrapo** [comment] 2019-07-17 12:22
was it fixed?
tried all the methods mentioned above and none of them work to me.

**Comment by s-razavi** [comment] 2020-06-29 22:22
I faced the same problem, for me, on Google Colab I imported df with ',' as delimiter where it was a mismatch to original data, I changed that to ';' and it worked.
