### ISSUE TITLE
macOS Big Sur 11.2 build fails

### ISSUE THREAD

**Issue by K20shores** [pandas-profiling/pandas-profiling#694] opened 2021-02-10 17:00 UTC
**Describe the bug**

`pip install pandas-profiling` fails

```
...
Installing collected packages: llvmlite, visions, numba, imagehash, phik, missingno, htmlmin, confuse, pandas-profiling
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/kyle/Documents/HoustonPM2.5/houston/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/setup.py'"'"'; __file__='"'"'/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-record-bgb5soeg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/kyle/Documents/HoustonPM2.5/houston/include/site/python3.9/llvmlite
         cwd: /private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Users/kyle/Documents/HoustonPM2.5/houston/bin/python3.9 /private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/kyle/Documents/HoustonPM2.5/houston/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/kyle/Documents/HoustonPM2.5/houston/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/setup.py'"'"'; __file__='"'"'/private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-install-icj2prdi/llvmlite_c0d93101e8924b1998f9b86ff33fe3b4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j8/13gdnhs51_g_jl1wlxj7h3tm0000gn/T/pip-record-bgb5soeg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/kyle/Documents/HoustonPM2.5/houston/include/site/python3.9/llvmlite Check the logs for full command output.
```

**To Reproduce**

Have a mac with the above version operating system. `pip install pandas-profiling`

**Version information:**

```
Python version_: Python 3.9.1
Environment: Command line
Pip: pip 21.0.1
```

**Additional context**

Sorry if the above isn't formatted properly. How to format was confusing

**Comment by sbrugman** [comment] 2021-02-10 18:41
Possible duplicate of https://github.com/pandas-profiling/pandas-profiling/issues/594 (please check if that solution helps you).

**Closed** 2021-02-21 11:58 UTC
Labels: needs more information ❔
