### ISSUE TITLE
The values ​​of 'Total Missing (%)' and frecuency in toggle details  do not appear and the plot at the right of the variables is not filled,

### ISSUE THREAD

**Issue by Scruz2016** [pandas-profiling/pandas-profiling#137] opened 2018-08-13 09:43 UTC
![sin titulo](https://user-images.githubusercontent.com/22541214/44024682-43bc786a-9eee-11e8-97ad-e75b49d56044.png)
![sin titulo2](https://user-images.githubusercontent.com/22541214/44024626-1ebea952-9eee-11e8-9511-76471306ff91.png)

**Comment by vr00n** [comment] 2019-03-04 15:33
I have the same issue

**Comment by dunce1** [comment] 2019-04-25 14:49
Anyone have any workarounds for this issue? I'm having the same issues as well! Using Python 2.7.

**Comment by vr00n** [comment] 2019-04-26 15:21
@dunce1  Don't count on it being solved.
via the README.
```
This package does not have a current active maintainer. If you are interested to take on the role of main developer, feel free to reach out to @JosPolfliet.
```

**Comment by bruinAlex** [comment] 2019-04-26 17:58
Just wondering what versions of dependencies everyone with the problem is working from. I tried downloading a larger dataset of randomly generated data from [here](http://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/) since my own datasets are nowhere near the size of what's in the screenshots. I haven't come across the same issues yet in my smaller work datasets or the random data, but I am curious what is causing this issue.

- Windows 10
- Python 3.7.0
- pandas 0.23.4
- pandas-profiling 1.4.1
- matplotlib 2.2.3
- six 1.11.0
- jupyter 1.0.0

**Comment by JosPolfliet** [comment] 2019-04-27 08:34
Looks good here. Can you do a `pip freeze` and share the outputs so we can try to reproduce?

**Comment by sbrugman** [comment] 2019-05-29 15:17
The issue seems to be resolved in the latest version, please let us know otherwise.

**Closed by sbrugman** 2019-05-29 15:17 UTC
