### ISSUE TITLE
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

### ISSUE THREAD

**Issue by eyadsibai** [pandas-profiling/pandas-profiling#49] opened 2017-06-27 12:18 UTC
```  File "/python3.6/site-packages/pandas_profiling/base.py", line 59, in describe_numeric_1d
    stats['range'] = stats['max'] - stats['min']
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```
I got this error

**Comment by tejaslodaya** [comment] 2017-07-04 08:13
Boolean values shouldn't enter `describe_numeric_1d` function. It must be treated as Categorical.

Can you provide a snapshot of the data you're running it on?
Or the datatype may also help.

**Comment by eyadsibai** [comment] 2017-07-04 10:08
I had a boolean column using latest numpy version... and pandas 0.20.2

**Comment by tejaslodaya** [comment] 2017-07-04 10:22
In `base.py` file, go to line number 59.
Change 
`stats['range'] = stats['max'] - stats['min']`
to 
`stats['range'] = np.subtract(stats['max'], stats['min'], dtype=np.float32)`
and report the results.

**Comment by tejaslodaya** [comment] 2017-07-04 13:36
@eyadsibai Does it work?
I couldn't reproduce the results. So, bear with me for some manual editing.

**Comment by eyadsibai** [comment] 2017-08-06 19:02
Yes I believe this solves the problem!

**Comment by chinmaythosar** [comment] 2018-02-16 16:07
yep. had a similar issue where series.py at line ~1800 had to manually edit
'good = -bad' to 'good = ~bad'

surprisingly even when I commented the first line to add the second it game me an error saying  - is not supported ...

**Comment by Rubyguanzi** [comment] 2018-11-16 09:50
I also got this error ，and then check the numpy version numpy1.8.1 can ，but 1.5.1 not

**Comment by jvschoen** [comment] 2020-01-13 17:59
Still encountering this error when going through a GCP tutorial:
https://cloud.google.com/solutions/building-a-propensity-model-for-financial-services-on-gcp
Trying to run the 2nd cell in section 2) Data Exploration.

**Comment by sbrugman** [comment] 2020-01-13 18:17
@jvschoen thank you for reporting this issue. Are you in the position to export the data frame (for example .csv) and post it here easily? 

Without using BigQuery, the code seems to work just fine:
```
# As features on the Google Cloud Platform website:
# https://cloud.google.com/solutions/building-a-propensity-model-for-financial-services-on-gcp


import pandas as pd

from pandas_profiling import ProfileReport


if __name__ == "__main__":
    df = pd.read_csv('https://storage.googleapis.com/erwinh-public-data/bankingdata/bank-full.csv', sep=';')

    profile = ProfileReport(df, title="GCP Banking Data")
    profile.to_file('gcp_banking_report.html', silent=False)
```

**Comment by jvschoen** [comment] 2020-01-13 22:09
@sbrugman I worked through a force update earlier that worked, but this seems a bit cleaner approach. I'll edit it in my notebook and run accordingly in the future. Thanks for the quick response and solution!

**Comment by jvschoen** [comment] 2020-02-12 15:42
To add to this thread. This solution will break the notebook instance and you can no longer access the jupyterlab. you'll need to ssh in to troubleshoot. However, I did figure out you need to `pip uninstall attr` then `pip install attrs` before shutting down your instance to ensure jupyter starts up properly. I know this is a bit of a tangent from the question, and more of an issue with GCP, but just wanted to make sure if someone tried this solution they may run into issues getting back into their AI notebook.

**Comment by joshtemple** [comment] 2020-04-23 19:54
What is the status of this issue? I'm getting the same error when trying to run the report in a JupyterLab notebook. It looks like solutions have been proposed (modifying the local version of the user's code), but no PRs are referenced or merged.

**Comment by sbrugman** [comment] 2020-04-25 12:21
@joshtemple 
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda)
    - packages (`pip freeze > packages.txt`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Closed** 2020-07-02 00:02 UTC
Labels: bug 🐛, help wanted 🙋, needs more information ❔, no-issue-activity
