### ISSUE TITLE
@fepre This still an issue with Pandas Profiling version 2.10.0.

### ISSUE THREAD

**Issue by JamesMDorame** [pandas-profiling/pandas-profiling#684] opened 2021-02-01 18:26 UTC
@fepre This still an issue with Pandas Profiling version 2.10.0.  

`import numpy as np
import pandas_profiling
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=["a", "b", "c", "d", "e"]
)
pandas_profiling.ProfileReport(df)`

_Originally posted by @JamesMDorame in https://github.com/pandas-profiling/pandas-profiling/issues/496#issuecomment-769953226_

**Comment by sbrugman** [comment] 2021-02-03 17:32
Duplicate of #685

**Closed by sbrugman** 2021-02-03 17:32 UTC
