### ISSUE TITLE
Warn for high correlations using Phi_K?

### ISSUE THREAD

**Issue by sobayed** [pandas-profiling/pandas-profiling#577] opened 2020-09-17 06:59 UTC
Is it possible to create high correlation warnings using the Phi_K coefficient instead of Pearson/Cramer? This would be helpful to identify correlations between variables of different types (e.g. bool & categorical). Right now, I can see the high correlations in the "Correlations" tab of the report, but trying to create warnings by changing the config results in an error:

```python
profile = ProfileReport(
    train, 
    title="Pandas Profiling Report", 
    minimal=False, 
    correlations={"phi_k": {"warn_high_correlations": True, "threshold": 0.9}}
)
```

```python
------------------------------------------------------------------
ValueError                       Traceback (most recent call last)
<ipython-input-11-a3db901f77b1> in <module>
----> 1 profile = ProfileReport(
      2     train,
      3     title="Pandas Profiling Report",
      4     minimal=False,
      5     correlations={"phi_k": {"warn_high_correlations": True, "threshold": 0.9}}

~/miniconda3/envs/temp/lib/python3.8/site-packages/pandas_profiling/profile_report.py in __init__(self, df, minimal, explorative, sensitive, dark_mode, orange_mode, sample, config_file, lazy, **kwargs)
     76             config.set_arg_group("orange_mode")
     77 
---> 78         config.set_kwargs(kwargs)
     79 
     80         self.df = None

~/miniconda3/envs/temp/lib/python3.8/site-packages/pandas_profiling/config.py in set_kwargs(self, kwargs)
    146         kwargs = self._handle_shorthands(kwargs)
    147 
--> 148         self._set_kwargs(self.config, kwargs)
    149 
    150     def __getitem__(self, item):

~/miniconda3/envs/temp/lib/python3.8/site-packages/pandas_profiling/config.py in _set_kwargs(self, reference, values)
     91             if key in reference:
     92                 if type(value) == dict:
---> 93                     self._set_kwargs(reference[key], value)
     94                 else:
     95                     reference[key].set(value)

~/miniconda3/envs/temp/lib/python3.8/site-packages/pandas_profiling/config.py in _set_kwargs(self, reference, values)
     91             if key in reference:
     92                 if type(value) == dict:
---> 93                     self._set_kwargs(reference[key], value)
     94                 else:
     95                     reference[key].set(value)

~/miniconda3/envs/temp/lib/python3.8/site-packages/pandas_profiling/config.py in _set_kwargs(self, reference, values)
     95                     reference[key].set(value)
     96             else:
---> 97                 raise ValueError(f'Config parameter "{key}" does not exist.')
     98 
     99     _shorthands = {

ValueError: Config parameter "threshold" does not exist.
```

UPDATE: Using a modified `config.yml` file instead seems to work, so the error seems to be related to the dictionary interface.

**Comment by sbrugman** [comment] 2020-09-17 16:35
@sobayed Thanks for reporting this. The issue is that the default config file does not have a `threshold` in that section, we should add it!

**Comment by sbrugman** [comment] 2020-09-18 20:19
Resolved in `develop`, will be out with the next release!

**Closed** 2020-09-18 20:23 UTC
